from setuptools import setup, find_packages

setup(
    name="kokbisa",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "google-api-python-client",
        "google-auth-oauthlib",
        "google-auth-httplib2",
        "youtube-transcript-api",
        "yt-dlp",
        "pyyaml",
        "pandas",
        "numpy",
        "pyarrow",
        "PySastrawi",
        "emoji",
        "spacy",
        "nltk",
        "scikit-learn",
        "transformers",
        "sentence-transformers",
        "umap-learn",
        "matplotlib",
        "seaborn",
        "plotly",
        "dash",
        "pyvis",
        "networkx",
        "python-dotenv",
        "ipykernel",
        "tqdm",
        "langdetect",
    ],
    description="Indonesian Public Discourse in YouTube-Based Science Communication Corpus Pipeline",
    author="Scientific Researcher",
)
